### ISSUE TITLE
Replace Candlekeep image in Prologue

### ISSUE THREAD

**Issue by tomasz1986** [Sampsca/BGEE-Classic-Movies#3]
The mod seems to cover almost all of the original movies and pictures, but the one used in the Prologue seems to be missing.

To be specific, BG:EE uses

![image](https://user-images.githubusercontent.com/5626656/94356818-8be0e700-00cd-11eb-94c4-90b3d2d3ba24.png)

while the original BG1 used

![image](https://user-images.githubusercontent.com/5626656/94356820-91d6c800-00cd-11eb-8e89-79752b888b73.png)

Would it be possible to replace the current one with the original image?

**Comment by Sampsca** [comment]
This is BGEE v2.5.15.1 
![Baldr007](https://user-images.githubusercontent.com/7087647/94370513-1d445f00-00b6-11eb-9a38-8c63b6ed3b52.png)
It has definitely already been replaced.  Are you using any GUI mods?

**Comment by tomasz1986** [comment]
Hmm, yeah, I am using the lefreut's Enhanced UI (https://github.com/r-e-d/LeUI-BG1EE). By reading the forum thread on the SHS forum, I thought the mod was supposed to be compatible with it, but maybe I was wrong?

Now, by reading into it, it may be the same problem as explained in http://www.shsforums.net/topic/55573-mod-bgee-classic-movies/page-4#entry605352.

I am using BG:EE 2.5.17.0 from GOG with no other additions like SoD, etc.

**Comment by Sampsca** [comment]
I have a guess as to what has happened, but I'll need to look into it a bit more to be sure.  It also looks like there's an opportunity to support other themes.  Unfortunately I'm going to be pretty busy this week.  Will probably have a bit more free time next week.

**Comment by Sampsca** [comment]
I'm still working on at least one other optimization and perhaps support for additional themes, but in the meantime I just pushed new commits (not releases) that you're welcome to test.  Ideally, testing BGEE and SoD each with and without LeUI-BG1EE would be helpful to make sure I fixed the problem without breaking anything.

**Comment by tomasz1986** [comment]
Thank you for the update. I have tested with BGEE, and at least the Prologue screen has the classic image. I will be checking the rest while playing. I do not have SoD, so I cannot test that, unfortunately.

**Comment by Sampsca** [comment]
The afore mentioned optimization and support for additional themes have been added to the latest commit.  If public testing goes well, I'll make a formal release of it.  As you say the issues seems to have been resolved, I'll close the issue for now.

**Comment by tomasz1986** [comment]
Thank you for the fixes. I have just tried the current version, but there seem to be an issue when trying to install the movies. The chapter and dream screens do install fine.

```
WARNING: POSSIBLE ERROR: file BEREGOST.mve is not found in action 167.
WARNING: POSSIBLE ERROR: file TAVERN.mve is not found in action 167.
```

**Comment by Sampsca** [comment]
Sorry, that's a minor bug with WeiDU's MODDER flag.  I have [pointed it out](https://forums.pocketplane.net/index.php?topic=29953.msg340412#msg340412) to Wisp.  You can safely ignore those two warnings.

**Comment by Sampsca** [comment]
Just pushed a commit to disable the MODDER flag for now.
