### ISSUE TITLE
Classic chapter screens and dreams still not working with LeUI

### ISSUE THREAD

**Issue by ap3nr0ts** [Sampsca/BGEE-Classic-Movies#5]
Hi. I wanted to tell you via the topic on Spellhold Studios, but the captcha keeps bugging out ... I can't complete it. I have the BG1 version of LeUI and I still don't get the old chapter screens. This is my list of mods, and I've used the link you gave in the topic on Spellhold:

~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3030 // Easy Spell Learning -> 100% Learn Spells: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3310 // Start New Games with Party AI Turned Off: v9
~BGEECLASSICMOVIES/BGEECLASSICMOVIES.TP2~ #0 #0 // Restore BG1 movies to BG:EE -> Replace all movies: v2.3.0
~BGEECLASSICMOVIES/BGEECLASSICMOVIES.TP2~ #0 #3 // Restore BG1 Chapter and Dream Screens: v2.3.0
~LEUI-BG1EE/LEUI-BG1EE.TP2~ #0 #0 // lefreut's Enhanced UI (BG1EE skin) - Core component: 4.2
~LEUI-BG1EE/LEUI-BG1EE.TP2~ #0 #1 // lefreut's Enhanced UI (BG1EE skin) - BG2 vanilla bams for spells: 4.2
~LEUI-BG1EE/LEUI-BG1EE.TP2~ #0 #2 // lefreut's Enhanced UI (BG1EE skin) - BG2 vanilla fonts for descriptions: 4.2
~LEUI-BG1EE/LEUI-BG1EE.TP2~ #0 #3 // lefreut's Enhanced UI (BG1EE skin) - Disable item comparison feature: 4.2
~A7-CONVENIENTEENPCS/SETUP-A7-CONVENIENTEENPCS.TP2~ #0 #1 // Modify Enhanced Edition NPCs -> Disable all NPCs: v4.1
~A7-CONVENIENTEENPCS/SETUP-A7-CONVENIENTEENPCS.TP2~ #0 #301 // Make NPC-specific items available for everyone: v4.1

If you need any more info, please let me know. :)

**Comment by Sampsca** [comment]
Classic Movies must be installed AFTER LEUI.

**Comment by ap3nr0ts** [comment]
Ah. Thanks. I reinstalled that option after the first try, but I guess it
just reinstalled everything I already had after that again? Please correct
me if I'm wrong, but installing everything from scratch should fix it? LeUI
first, your mod second, then the other 2?

Op wo 28 okt. 2020 21:17 schreef Sampsca <notifications@github.com>:

**Comment by Sampsca** [comment]
Reinstalling a mod in the middle of your install order does the following:
1. Uninstalls all mods that were installed after that mod
2. Uninstalls that mod
3. Installs that mod
4. Installs all mods that were previously installed after that mod

At best, this does nothing to unchanged mods.  At worst, it breaks your game.  I recommend starting over with a clean install.  I can't speak to the proper order of the other mods, but Classic Movies must be installed after any of the LEUI variants (and after EET and its GUI mod).

**Comment by ap3nr0ts** [comment]
Thanks!

You can add another "it seems to work fine" to your list then. This order worked great:

CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3030 // Easy Spell Learning -> 100% Learn Spells: v9
CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3310 // Start New Games with Party AI Turned Off: v9
A7-CONVENIENTEENPCS/SETUP-A7-CONVENIENTEENPCS.TP2~ #0 #1 // Modify Enhanced Edition NPCs -> Disable all NPCs: v4.1
A7-CONVENIENTEENPCS/SETUP-A7-CONVENIENTEENPCS.TP2~ #0 #301 // Make NPC-specific items available for everyone: v4.1
LEUI-BG1EE/LEUI-BG1EE.TP2~ #0 #0 // lefreut's Enhanced UI (BG1EE skin) - Core component: 4.2
LEUI-BG1EE/LEUI-BG1EE.TP2~ #0 #1 // lefreut's Enhanced UI (BG1EE skin) - BG2 vanilla bams for spells: 4.2
LEUI-BG1EE/LEUI-BG1EE.TP2~ #0 #2 // lefreut's Enhanced UI (BG1EE skin) - BG2 vanilla fonts for descriptions: 4.2
LEUI-BG1EE/LEUI-BG1EE.TP2~ #0 #3 // lefreut's Enhanced UI (BG1EE skin) - Disable item comparison feature: 4.2
BGEECLASSICMOVIES/BGEECLASSICMOVIES.TP2~ #0 #0 // Restore BG1 movies to BG:EE -> Replace all movies: v2.3.0
BGEECLASSICMOVIES/BGEECLASSICMOVIES.TP2~ #0 #3 // Restore BG1 Chapter and Dream Screens: v2.3.0
