### ISSUE TITLE
PS Gui available?

### ISSUE THREAD

**Issue by electricsheep82** [Sampsca/BGEE-Classic-Movies#9]
Hi; sorry, this isn't really an issue with this repo, but I was trying to find a copy of your PS GUI tool, and the only place I can find it is shsforums, which has been down for a while. Is there a way you could make it available somewhere else please? I'm trying to do the same upconvert of these videos, except to work with GemRB, not EE. Thank you!

**Comment by Sampsca** [comment]
[PS gui v3.04.rar](http://classicadventuresmod.com/modmirror/PS%20gui%20v3.04.rar)
FYI, ffmpeg can also convert the movies from the Interplay MVE format
